---
- name: Ansible Create user functionlity module demo
  hosts: ubuntu
# Defining the remote server where the ansible create user module will manage the objects
  # remote_user: ubuntu   # Using Remote user as ubuntu
  tasks:
    - name: Add the user 'Matt' with a specific uid and a primary group of 'sudo'
      ansible.builtin.user:
        name: abhinav
        comment: abhinav in devops
        uid: 1055
        group: abhinav
        password: 'qwerty1234'
        createhome: yes     # Defaults to yes
        home: /home/abhinav    # Defaults to /home/<username>